FROM php:8.3-cli

WORKDIR /app

# For local build testing
ARG proxy
RUN if [[ -z "$proxy" ]] ; then echo 'Acquire::http { Proxy "http://home1.quud.net:3142"; };' >> /etc/apt/apt.conf.d/01proxy ; fi

RUN apt update \
    && apt install -y unzip git \
    && docker-php-ext-install pdo pdo_mysql

COPY --from=composer:2.6 /usr/bin/composer /usr/local/bin/composer
